Improve error reporting when no backend is found
This used to spit out

	  File "updian/fabric_utils.py", line 52, in _detect_backend
	    backend = available_backends[0]
	IndexError: list index out of range

now we get at least

	UnknownBackendError: Unknown backend: None

Note that the actual problem is usually a missing (or not executable)
updian-rsh on the remote side.